"Supreme",
"Murray's",
"Alta Langa",
"Murray's",
"Lactalis",
"Fromagerie Guilloteau",
"Fromagerie Guilloteau",
"Fromagerie Guilloteau",
"Cypress Grove",
"Alta Langa",
"Murray's",
"Cowgirl Creamery",
"Alta Langa",
"Fromagerie Guilloteau",
"Belletoile",
"Cypress Grove",
"Point Reyes",
"Black River",
"Murray's",
"Roth Kase",
"Champignon",
"Kerrygold",
"Rogue Creamery",
"Murray's",
"Ciresa",
"Ciresa",
"Point Reyes",
"Rogue Creamery",
"Rogue Creamery",
"Salemville®",
"Salemville®",
"Murray's",
"Murray's",
"Beehive Cheese Company",
"Cellars At Jasper Hill",
"SOMERDALE",
"Spring Green",
"Spring Green",
"Old Croc",
"Mrs. Quicke's",
"Beecher's Handmade Cheese",
"Murray's",
"Murray's",
"Murray's",
"Beehive",
"Beehive",
"Westminster",
"Old Croc",
"Murray's",
"Westminster",
"Murray's",
"Rocking W",
"Somerdale",
"Belgioioso",
"Somerdale",
"Long Clawson",
"Murray's",
"Kerrygold",
"Cello",
"Rocking W",
"Maple Leaf",
"New Bridge",
"Parrano",
"Murray's",
"Maple Leaf",
"Rocking W",
"Kaamps",
"Cello Cheese",
"Beehive Cheese",
"Cello Cheese",
"Long Clawson",
"Rocking W",
"Somerdale",
"Rembrandt",
"Brugge",
"Best Cheese",
"Murray's",
"Frans Hals",
"Murray's",
"Holland's Family Cheese",
"Thise Dairy",
"Parrano",
"Maple Leaf",
"Maple Leaf",
"Maple Leaf",
"Kaamps",
"Sartori",
"Sartori",
"Sartori",
"Sartori",
"Sartori",
"Murray's",
"Murray's",
"Murray's",
"Sartori",
"Sartori",
"Roth Kase",
"Murray's",
"Murray's",
"Murray's",
"Murray's",
"Ciresa",
"Roth Kase",
"Roth Kase",
"Murray's",
"Roth Kase",
"Roth Kase",
"Norseland",
"Maple Leaf",
"New Bridge",
"Murray's",
"Kaseri Studer",
"Emmi",
"Emmi",
"Murray's",
"Mitica",
"Hofkäserei Kraus",
"Haystack Mountain",
"Mitica",
"Mitica",
"Isigny",
"Uplands Farm",
"Haystack Mountain",
"Mitica",
"Mitica",
"Murray's",
"Spring Brook Farm",
"Cowgirl Creamery",
"CIRESA",

var names = ["Mike","Matt","Nancy","Adam","Jenny","Nancy","Carl"];
var uniqueNames = [];
$.each(names, function(i, el){
    if($.inArray(el, uniqueNames) === -1) uniqueNames.push(el);
});